import { Col, Row, Select, Typography } from 'antd'
import Head from 'next/head'
import { useState } from 'react'
import Layout from '~/components/Layout'
import PredictJPEG from '~/components/PredictJPEG'
import PredictionTable from '~/components/PredictionTable'
import UploadPDF from '~/components/UploadPDF'
import type {
  DrawingComponent,
  LineType,
  MissingComponent,
  RemainingComponent,
} from '~/models/drawings.model'

export default function Home() {
  // hooks
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [lineTypes, setLineTypes] = useState<LineType[]>([])
  const [drawingComponents, setDrawingComponents] = useState<DrawingComponent[]>([])
  const [missingComponents, setMissingComponents] = useState<MissingComponent[]>([])
  const [remainingComponents, setRemainingComponents] = useState<RemainingComponent[]>([])

  const handleChange = (value: string) => {
    console.log(`selected ${value}`)
  }

  return (
    <Layout>
      <Head>
        <title>ASDR: Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row justify="center" align="middle">
        {/* Title */}
        <Col span={24}>
          <Typography.Title level={4}>Diagnose a Drawing</Typography.Title>
        </Col>
      </Row>

      <Row justify="center" align="middle" gutter={[16, 16]}>
        {/* Select the type of drawing */}
        <Col
          span={24}
          style={{
            textAlign: 'center',
          }}>
          <Typography.Title level={4}>Select the type of drawing</Typography.Title>
          <Select
            defaultValue="mt"
            onChange={handleChange}
            options={[
              { value: 'mt', label: 'Main & Transfer' },
              { value: 'h', label: 'H-config' },
              { value: 'bh', label: 'Breaker & a Half' },
              { value: 'dbsb', label: 'Double Bus Single Breaker' },
            ]}
          />
        </Col>

        {/* Upload a PDF file*/}
        <Col
          span={24}
          style={{
            textAlign: 'center',
          }}>
          <UploadPDF imageFile={imageFile} setImageFile={setImageFile} />
        </Col>

        {/* Send to prediction */}
        <Col
          span={6}
          style={{
            textAlign: 'center',
          }}>
          <PredictJPEG
            imageFile={imageFile}
            lineTypes={lineTypes}
            setLineTypes={setLineTypes}
            drawingComponents={drawingComponents}
            setDrawingComponents={setDrawingComponents}
            missingComponents={missingComponents}
            setMissingComponents={setMissingComponents}
            remainingComponents={remainingComponents}
            setRemainingComponents={setRemainingComponents}
          />
        </Col>

        {/* Display prediction */}
        <Col
          span={24}
          style={{
            textAlign: 'center',
          }}>
          <PredictionTable
            lineTypes={lineTypes}
            setLineTypes={setLineTypes}
            drawingComponents={drawingComponents}
            setDrawingComponents={setDrawingComponents}
            missingComponents={missingComponents}
            setMissingComponents={setMissingComponents}
            remainingComponents={remainingComponents}
            setRemainingComponents={setRemainingComponents}
          />
        </Col>
      </Row>
    </Layout>
  )
}
