import { Col, Row, Select, Typography } from "antd";
import Head from "next/head";
import Layout from "~/components/Layout";
import UploadPDF from "~/components/UploadPDF";

export default function Home() {
  const handleChange = (value: string) => {
    console.log(`selected ${value}`);
  };

  return (
    <Layout>
      <Head>
        <title>
          ASDR: Automatic System to Diagnose and Recognize Electrical Drawings
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row justify="center" align="middle">
        {/* Title */}
        <Col span={24}>
          <Typography.Title level={3}>
            ASDR: Automatic System to Diagnose and Recognize Electrical Drawings
          </Typography.Title>
        </Col>
      </Row>

      <Row justify="center" align="middle" gutter={[16, 16]}>
        {/* Select the type of drawing */}
        <Col
          span={24}
          style={{
            textAlign: "center",
          }}
        >
          <Typography.Title level={5}>
            Select the type of drawing
          </Typography.Title>
          <Select
            defaultValue="mt"
            onChange={handleChange}
            options={[
              { value: "mt", label: "Main & Transfer" },
              { value: "h", label: "H-config" },
              { value: "bh", label: "Breaker & a Half" },
              { value: "dbsb", label: "Double Bus Single Breaker" },
            ]}
          />
        </Col>

        {/* Upload a PDF file*/}
        <Col
          span={6}
          style={{
            textAlign: "center",
          }}
        >
          <UploadPDF />
        </Col>
      </Row>
    </Layout>
  );
}
