import { Container } from '@mui/material'
import Head from 'next/head'
import MLServer from '~/components/MLServer'

export default function Server() {
  return (
    <>
      <Head>
        <title>asdr: Machine Learning Server</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <MLServer />
      </Container>
    </>
  )
}
